#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

case "$1" in
  configure)
    #chown kafka:kafka /var/log/kafka
    if [ -f /etc/init.d/kafka ];then
      chown 0:0 /etc/init.d/kafka
      update-rc.d kafka defaults 98 02
    fi
    chown -R 0:0 /etc/kafka
    chown 0:0 /etc/security/limits.d/kafka-nofiles.conf
    chown -R 0:0 /usr/lib/kafka
    chown 0:0 /etc/default/kafka
    chown 0:0 /etc/logrotate.d/kafka
   ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0

