#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

chown kafka:kafka /var/log/kafka
# when created on a mac, user is 501 :(
chown -R root:root /etc/init.d/kafka
chown -R root:root /etc/kafka
chown -R root:root /etc/security/limits.d/kafka-nofiles.conf
chown -R root:root /usr/lib/kafka
chown -R root:root /etc/default/kafka
chown -R root:root /etc/logrotate.d/kafka
update-rc.d kafka defaults 98 02
exit 0

